Added Domoticz as application using the MQTT Discover function.
zwave-js/zwavejs2mqtt pull request #2019
Opened 2021-12-03 16:14 UTC by waltervl

See also https://www.domoticz.com/wiki/ZwaveJS2MQTT

2021-12-03 16:21 UTC, robertsLando commented
@waltervl Please add it as a new entry in the list

2021-12-03 18:26 UTC, waltervl commented
Thank you for reviewing. Modified as requested.

2021-12-04 13:30 UTC, robertsLando requested changes

2021-12-04 13:30 UTC, robertsLando commented on docs/README.md
> +- **Supported by Domoticz (beta 2021.1) using MQTT Autodiscovery.
```suggestion
- **Supported by Domoticz** (beta 2021.1) using MQTT Autodiscovery. 
```

2021-12-06 12:56 UTC, waltervl commented
It should be resolved now or did I miss something in the github review process?

2021-12-06 12:58 UTC, robertsLando approved these changes

2021-12-06 12:58 UTC, merged