feat(ui): add active indicator with statistics tooltip
zwave-js/zwavejs2mqtt pull request #2083
Opened 2021-12-20 13:38 UTC by robertsLando

Fixes #2070

2021-12-20 20:16 UTC, AlCalzone requested changes
The arrows seem to be switched. At least I'd assume that <- means incoming and -> means outgoing, but it is the opposite way.

2021-12-21 09:26 UTC, AlCalzone commented
If this can wait until tonight, I can try again.

2021-12-21 09:57 UTC, robertsLando commented
I can wait :) When ok just approve the pr and it will be merged

2021-12-21 14:38 UTC, AlCalzone approved these changes

2021-12-21 14:38 UTC, merged