adjust path and period, to prevent hitting ratelimit
zwave-js/zwavejs2mqtt pull request #2543
Opened 2022-07-22 21:12 UTC by kenthua

- The liveness check is too often, that it hits the rate limit threshold and prevents access to the UI
- Adjusted the health check path

2022-07-25 07:32 UTC, robertsLando requested changes

2022-07-25 07:32 UTC, robertsLando commented on kubernetes/deployment.yaml
> +            path: /health/zwave
`/health` api is more generic, it also checks for mqtt status (if it's not disabled)

2022-07-27 01:18 UTC, kenthua commented
updated, thanks @robertsLando

2022-07-27 06:12 UTC, robertsLando approved these changes

2022-07-27 06:13 UTC, merged