[feat] Publish binary sensors when notifications has only two states
zwave-js/zwavejs2mqtt pull request #396
Opened 2021-01-30 19:10 UTC by billiaz

Try to make Notifications better, byt creating HASS binary sensors.

- [ ] cover as much as possible sensors
- [ ] Make variables names better
- [ ] Possibly improve flow

2021-01-30 19:14 UTC, robertsLando requested changes
Looks good @billiaz ! :)

2021-01-30 19:14 UTC, robertsLando commented on lib/Gateway.js
> +        if (valueId.hasOwnProperty('states')) {
Use the util method "hasProperty" here

2021-01-30 19:47 UTC, billiaz commented on lib/Gateway.js
> +        if (valueId.hasOwnProperty('states')) {
hasProperty is not working :\

2021-01-31 22:44 UTC, blhoward2 commented
Ok, I've tested this. I see the new binary sensors under the zwavejs2mqtt front-end for the node (130 in this case), but they never appears in HA. I even tried rediscovering the node and multiple restarts of HA. You'll see more than one startup in the js log because I realized I had mqtt logging turned off. You'll also see that I hate to wake the water sensor a few times but ultimately it went to interview complete.

[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/5900903/zwavejs_1.log)
[zwavejs2mqtt.log.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5900907/zwavejs2mqtt.log.zip)
[node_130.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5900909/node_130.json.zip)

2021-02-01 07:01 UTC, billiaz reviewed
> Ok, I've tested this. I see the new binary sensors under the zwavejs2mqtt front-end for the node (130 in this case, an Aeotec Water Sensor 6), but they never appears in HA. I even tried rediscovering the node and multiple restarts of HA. You'll see more than one startup in the js log because I realized I had mqtt logging turned off. You'll also see that I had to wake the water sensor a few times but ultimately it went to interview complete.
> 
> [zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/5900903/zwavejs_1.log)
> [zwavejs2mqtt.log.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5900907/zwavejs2mqtt.log.zip)
> [node_130.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5900909/node_130.json.zip)

I do see the binary sensors are generated for HASS.
I suspect something breaks in hass. to get an entity error frm HASS is good to have DEBUG on (been there!)

```json
        "binary_sensor_cover_status": {
            "type": "binary_sensor",
            "object_id": "cover_status",
            "discovery_payload": {
                "payload_on": 3,
                "payload_off": 0,
                "value_template": "{{ value_json.value }}",
                "device_class": "opening",
                "state_topic": "homeassistant/130/113/0/Home_Security/Cover_status",
                "json_attributes_topic": "homeassistant/130/113/0/Home_Security/Cover_status",
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xeb87ad4a_node130"
                    ],
                    "manufacturer": "AEON Labs",
                    "model": "Water Sensor 6 (ZW122)",
                    "name": "nodeID_130",
                    "sw_version": "1.6"
                },
                "name": "nodeID_130_cover_status",
                "unique_id": "zwavejs2mqtt_0xeb87ad4a_130-113-0-Home_Security-Cover_status"
            },
            "discoveryTopic": "binary_sensor/nodeID_130/cover_status/config",
            "values": [
                "113-0-Home Security-Cover status"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        },
```

another:
```json
        "binary_sensor_water_alarm_1": {
            "type": "binary_sensor",
            "object_id": "water_alarm_1",
            "discovery_payload": {
                "payload_on": 2,
                "payload_off": 0,
                "value_template": "{{ value_json.value }}",
                "device_class": "None",
                "state_topic": "homeassistant/130/113/1/Water_Alarm/Sensor_status",
                "json_attributes_topic": "homeassistant/130/113/1/Water_Alarm/Sensor_status",
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xeb87ad4a_node130"
                    ],
                    "manufacturer": "AEON Labs",
                    "model": "Water Sensor 6 (ZW122)",
                    "name": "nodeID_130",
                    "sw_version": "1.6"
                },
                "name": "nodeID_130_water_alarm_1",
                "unique_id": "zwavejs2mqtt_0xeb87ad4a_130-113-1-Water_Alarm-Sensor_status"
            },
            "discoveryTopic": "binary_sensor/nodeID_130/water_alarm_1/config",
            "values": [
                "113-1-Water Alarm-Sensor status"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        },
```

```json
        "binary_sensor_water_alarm_2": {
            "type": "binary_sensor",
            "object_id": "water_alarm_2",
            "discovery_payload": {
                "payload_on": 2,
                "payload_off": 0,
                "value_template": "{{ value_json.value }}",
                "device_class": "None",
                "state_topic": "homeassistant/130/113/2/Water_Alarm/Sensor_status",
                "json_attributes_topic": "homeassistant/130/113/2/Water_Alarm/Sensor_status",
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xeb87ad4a_node130"
                    ],
                    "manufacturer": "AEON Labs",
                    "model": "Water Sensor 6 (ZW122)",
                    "name": "nodeID_130",
                    "sw_version": "1.6"
                },
                "name": "nodeID_130_water_alarm_2",
                "unique_id": "zwavejs2mqtt_0xeb87ad4a_130-113-2-Water_Alarm-Sensor_status"
            },
            "discoveryTopic": "binary_sensor/nodeID_130/water_alarm_2/config",
            "values": [
                "113-2-Water Alarm-Sensor status"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        }
    },
```

i notice they have class as None! I will tryt o fit a class to make them look nicer.

from this link https://www.home-assistant.io/integrations/binary_sensor/#device-class

I suggest to use "moisture" or "problem" class.
I tend to believe moisture might fit better.

2021-02-01 09:04 UTC, robertsLando requested changes

2021-02-01 09:04 UTC, robertsLando commented on lib/Gateway.js
> +  )
```suggestion
  const stateKeys = valueId.states.map(s => s.value)
```

2021-02-01 09:04 UTC, robertsLando commented on lib/Gateway.js
> +            cfg = getBinaryPayloadFromSensor(cfg, valueId, off)
```suggestion
            cfg = setBinaryPayloadFromSensor(cfg, valueId, off)
```

2021-02-01 09:32 UTC, billiaz commented on lib/Gateway.js
> +            cfg = getBinaryPayloadFromSensor(cfg, valueId, off)
Agree, done this change

2021-02-01 09:33 UTC, billiaz commented on lib/Gateway.js
> +  for (const listKey in states) {
should be array. of is different? will check it

2021-02-01 09:33 UTC, billiaz commented on lib/Gateway.js
> +function getBinaryPayloadFromSensor (cfg, devicePayload, off = 0) {
made some more changes on this bit

2021-02-01 09:36 UTC, billiaz commented on lib/Gateway.js
> +  )
done! thanks!

2021-02-01 09:44 UTC, robertsLando requested changes

2021-02-01 09:44 UTC, robertsLando commented on lib/Gateway.js
> +function getMapFromArrayOfStates (states) {
@billiaz This can be removed now

2021-02-01 09:44 UTC, robertsLando commented on lib/Gateway.js
> + * @param {number} offStateValue The value number to consider off state
```suggestion
 * @param {import('../types').HassDevice} cfg Hass discovery Configuration
 * @param {import('../types').Z2MValueId} valueId The device ValueID
 * @param {number} offStateValue The value number to consider off state
```

2021-02-01 09:47 UTC, billiaz commented on lib/Gateway.js
> +  for (const listKey in states) {
it is an object/map and we extract the index of this. therefore (Reading a bit) for...in is better ?

2021-02-01 13:01 UTC, robertsLando submitted a review, later dismissed
LGTM. @billiaz Feedback? Is this working?

2021-02-01 13:17 UTC, billiaz commented
I got some nice additions from @blhoward2 as two sensors are discovered but as Generic! and might worth include them!
that all! other than this for me it worked like charm! 

@blhoward2 has a separate issue, which is causing his HASS not to discover

2021-02-01 14:07 UTC, blhoward2 commented
I'll try again tonight, my time. MQTT discovery has been working fine in other contexts so I'm not sure what the issue would be.

2021-02-01 14:16 UTC, robertsLando commented
@billiaz This looks good to me, so if @blhoward2 feedback is ok I will merge this or let you do that :)

2021-02-01 14:21 UTC, aretakisv commented
I am adding a definition for notification device_classes to cover waterleak
i will put these under Moisture device_class

2021-02-01 14:28 UTC, aretakisv commented
@robertsLando it is ready!

2021-02-01 14:39 UTC, robertsLando approved these changes

2021-02-01 14:39 UTC, merged

2021-02-02 02:31 UTC, blhoward2 commented
@robertsLando @billiaz Hey guys, I think we need to revert this. So contact sensors aren't the only ones with two values sending basic set events. Double tap also works that way and this breaks it. We need to make sure it is actually a water sensor or whatever before we do this change.