Update homeassistant.md
zwave-js/zwavejs2mqtt pull request #417
Opened 2021-02-01 18:47 UTC by fanningert

Add example to execute scene from home assistant

2021-02-01 18:52 UTC, fanningert commented
https://github.com/zwave-js/zwavejs2mqtt/issues/387

2021-02-01 19:31 UTC, chilicheech commented on docs/guide/homeassistant.md
> +In this example I will execute the scene with the id `1` via a switch, with following entries in the `configuration.yaml`. Replace `<mqtt_prefix>` and `<mqtt_name>` with you values.
`with your values`

2021-02-01 21:05 UTC, fanningert commented on docs/guide/homeassistant.md
> +In this example I will execute the scene with the id `1` via a switch, with following entries in the `configuration.yaml`. Replace `<mqtt_prefix>` and `<mqtt_name>` with you values.
A better variant?
```
In this example I will execute the scene with the id `1` via a switch. 
Replace `<mqtt_prefix>` and `<mqtt_name>` with you values and add this lines in the `configuration.yaml` of home assistant.
```

2021-02-02 07:19 UTC, robertsLando requested changes

2021-02-02 07:19 UTC, robertsLando commented on docs/guide/homeassistant.md
> +In this example I will execute the scene with the id `1` via a switch, with the following entries in the `configuration.yaml`. Replace `<mqtt_prefix>` and `<mqtt_name>` with your values.
```suggestion
## Manually create entities

When mqtt auto discovery and custom components aren't enough for your needs you can choose to manually create your entities in hass.

### Execute scene

If you need to create a switch that triggers a scene activation (using mqtt apis) you can use this example.

Add the following entriy in the `configuration.yaml`. Replace `<mqtt_prefix>` and `<mqtt_name>` with your values, based on your mqtt settings and `<sceneId>` with the scene you want to activate
```

2021-02-02 07:19 UTC, robertsLando commented on docs/guide/homeassistant.md
> +    payload_on: '{ "args": [ 1 ] }'
```suggestion
    payload_on: '{ "args": [ <sceneId> ] }'
```

2021-02-02 07:21 UTC, robertsLando commented
@zwave-js-bot fix lint

2021-02-02 07:26 UTC, merged