feat: Improved add remove device UX
zwave-js/zwavejs2mqtt pull request #419
Opened 2021-02-02 00:14 UTC by jarrettv

I'm not happy with having to compare to work with all these status strings. It feels like things could be cleaner if some of the logic happened upstream (perhaps `ZwaveClient.js`). However, it does seem to be working well.

2021-02-02 07:32 UTC, robertsLando requested changes

2021-02-02 07:32 UTC, robertsLando commented on src/components/ControlPanel.vue
> +        this.timer = setInterval(() => {
```suggestion
        this.addRemoveTimer = setInterval(() => {
```

Typo?

2021-02-02 11:49 UTC, jarrettv commented
nice catch @robertsLando. Also, should we update `nodes-management.md` with this PR?

2021-02-02 12:56 UTC, robertsLando requested changes

2021-02-02 12:56 UTC, robertsLando commented on src/components/ControlPanel.vue
> +      }
A cleaner way to do this is to create a `computed` property let's call this `controllerStatus` that returns `this.appInfo.controllerStatus` (or even better call it inclusionStatus and make the checks needed there) and then watch only that :)

2021-02-02 12:56 UTC, robertsLando commented on src/components/ControlPanel.vue
> +        : this.nodes.filter(x => x.status !== 'Removed').length
I would move this on the lower if case as it's not used by all

2021-02-02 12:56 UTC, robertsLando commented on src/components/ControlPanel.vue
> +        : this.nodes.filter(x => x.status !== 'Removed').length
What about wathing for node added and node removed socket events instead?

2021-02-02 13:00 UTC, robertsLando commented
> nice catch @robertsLando. Also, should we update nodes-management.md with this PR?

That would be good, yes :) Maybe with some screenshots even better

2021-02-02 18:42 UTC, robertsLando requested changes

2021-02-02 18:42 UTC, robertsLando commented on lib/ZwaveClient.js
> +    this.sendToSocket(socketEvents.onNodeAdded, zwaveNode)
```suggestion
    this.sendToSocket(socketEvents.nodeAdded, zwaveNode)
```

2021-02-02 18:42 UTC, robertsLando commented on src/components/ControlPanel.vue
> +      handler (newVal) {
You can make this cleaner:

`addRemoveEndDate(newVal) {}`

2021-02-02 18:42 UTC, robertsLando commented on src/components/ControlPanel.vue
> +    controllerStatus: {
Same

2021-02-02 18:42 UTC, robertsLando commented on src/components/ControlPanel.vue
> +      now: new Date(),
Don't use this var, calcolate it when needed

2021-02-02 18:42 UTC, robertsLando commented on src/components/ControlPanel.vue
> +    onAddRemoveStateChange (controllerStatus) {
I would move all the function content in the watch method, no need to pass the controllerStatus as it's a computed var

2021-02-02 18:42 UTC, robertsLando commented on src/components/ControlPanel.vue
> +      this.socket.off(socketEvents.nodeRemoved)
We should check if this off also disables the nodeRemoved handler in App.vue

2021-02-02 23:27 UTC, jarrettv commented
Semantic PR title / commit messages ???

2021-02-03 08:20 UTC, robertsLando requested changes
I have submitted a PR to your fork. Merge that and we are done here :)

2021-02-03 13:26 UTC, merged

2021-02-03 13:26 UTC, robertsLando commented
Thanks @jarrettv !