add node Location and node Name on Value metadata
zwave-js/zwavejs2mqtt pull request #57
Opened 2020-12-07 20:16 UTC by billiaz

MQTT is a powerfull tool. Using data from to generate graphs is a good approach. 
In tools like influxdb, you rely on the whole Payload read. Adding node Location and Name in metadata is a way to use and analyse the data

Added nodeLocation and nodeName as metadata, to help searching/storing data.

2020-12-08 21:57 UTC, robertsLando commented
@billiaz IMO this should be added in a configuration options like "add node info to payload" (available only for json and valueId payloads). Adding them to valueIds is not a good practice as it will be repeated. It should be added only before sending the payload

2020-12-09 07:11 UTC, robertsLando requested changes
Needs to be added only to the payload and make it configurable using options in the ui

2020-12-09 12:26 UTC, billiaz commented
> Needs to be added only to the payload and make it configurable using options in the ui

I suspect this https://github.com/zwave-js/zwavejs2mqtt/blob/03d4d0e6cb69a82156f588346ede71572ca85a2a/lib/Gateway.js#L291 is a good point to build the code.

Maybe is a better spot I cannot currently see

2020-12-09 17:03 UTC, robertsLando requested changes

2020-12-09 18:28 UTC, billiaz commented on lib/Gateway.js
> +      if (this.config.includeNodeInfo) {
I will add this. but just before this, there is a `data.value` which obviously has to work only if this is an object.

maybe is better to  make it
```
if (typeof data === 'object) {
  data.value = tmpVal
  if(this.config.includeNodeInfo) {
    data.nodeName = node.name
    data.nodeLocation = node.loc
  }
}
```

2020-12-10 07:44 UTC, robertsLando commented on lib/Gateway.js
> +      if (this.config.includeNodeInfo) {
I mean add this after the switch

2020-12-10 07:46 UTC, billiaz commented on lib/Gateway.js
> +      if (this.config.includeNodeInfo) {
I understand, my question is. if data.value assumes data is object, why only check the nodeName/Location in our case?
shouldn't data.value also be checked for the same  typeof?

2020-12-10 07:52 UTC, robertsLando commented on lib/Gateway.js
> +      if (this.config.includeNodeInfo) {
nope, in the switch we check for the payload type, later if the payload is an object and the includeNodeInfo flag is true we add the node info

2020-12-10 13:55 UTC, robertsLando requested changes

2020-12-10 13:55 UTC, robertsLando commented on lib/Gateway.js
> +  if (typeof data === 'object' && this.config.includeNodeInfo) {
```suggestion
  if (this.config.includeNodeInfo && typeof data === 'object') {
```

This order makes the check quicker

2020-12-10 14:13 UTC, robertsLando approved these changes
LGTM. Thanks @billiaz :pray:

2020-12-10 14:13 UTC, merged